# Generated by Django 2.0.9 on 2025-09-09 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacks', models.CharField(max_length=100)),
                ('feedback_date', models.CharField(max_length=100)),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='group_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='internal_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=100)),
                ('max_marks', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('SUBJECT_ALLOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject_allocation')),
            ],
        ),
        migrations.CreateModel(
            name='note_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='previous_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
            ],
        ),
        migrations.RenameModel(
            old_name='chat',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='message',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='FACULTY',
        ),
        migrations.AddField(
            model_name='attendance',
            name='SUBJECT_ALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.subject_allocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note_request',
            name='PREVIOUS_NOTES',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.previous_notes'),
        ),
        migrations.AddField(
            model_name='note_request',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AddField(
            model_name='group_chat',
            name='GROUP_MEMBER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group_member'),
        ),
    ]
