# Generated by Django 2.0.9 on 2025-09-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250909_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='subname',
        ),
    ]
