# Generated by Django 2.0.9 on 2025-12-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20251004_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note_request',
            name='payment_status',
        ),
    ]
