# Generated by Django 2.0.9 on 2025-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_note_request_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_request',
            name='payment_amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
