# Generated by Django 3.0 on 2026-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_note_request_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
