# Generated by Django 3.0 on 2026-01-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20260102_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
