"""collegeconnect URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from collegeconnect import settings
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome', views.welcome),
    path('', views.login1),
    path('login1post', views.login1post),
    path('changepwd',views.changepwd),
    path('changepwdpost',views.changepwdpost),
    path('Admin_home', views.Admin_home),
    path('Admin_add_dept',views.Admin_add_dept),
    path('deparmentaddpost',views.deparmentaddpost),
    path('Admin_view_dept',views.Admin_view_dept),
    path('Admin_edit_dept/<id>',views.Admin_edit_dept),
    path('departmenteditpost/<id>',views.departmenteditpost),
    path('departmentdltpost/<id>',views.departmentdltpost),
    path('Admin_add_staff/<id>',views.Admin_add_staff),
    path('staffaddpost/<id>',views.staffaddpost),
    path('Admin_view_staff',views.Admin_view_staff),
    path('Admin_edit_staff/<id>',views.Admin_edit_staff),
    path('staffeditpost/<id>',views.staffeditpost),
    path('staffdltpost/<id>',views.staffdltpost),
    path('staff_alloc/<id>',views.staff_alloc),
    path('allocate_sub/<id>',views.allocate_sub),
    path('Admin_add_course/<id>',views.Admin_add_course),
    path('courseaddpost/<id>',views.courseaddpost),
    path('Admin_view_course',views.Admin_view_course),
    path('Admin_edit_course/<id>',views.Admin_edit_course),
    path('courseeditpost/<id>',views.courseeditpost),
    path('Admin_delete_course/<id>',views.Admin_delete_course),
    path('Admin_add_subject/<id>',views.Admin_add_subject),
    path('subjectaddpost/<id>',views.subjectaddpost),
    path('Admin_view_subject',views.Admin_view_subject),
    path('Admin_edit_subject/<id>',views.Admin_edit_subject),
    path('subjecteditpost/<id>',views.subjecteditpost),
    path('Admin_delete_subject/<id>',views.Admin_delete_subject),
    path('Admin_add_student/<id>',views.Admin_add_student),
    path('studentaddpost/<id>',views.studentaddpost),
    path('Admin_view_student',views.Admin_view_student),
    path('Admin_edit_student/<id>',views.Admin_edit_student),
    path('studenteditpost/<id>',views.studenteditpost),
    path('studentdltpost/<id>',views.studentdltpost),
    path('Admin_add_notification',views.Admin_add_notification),
    path('notiaddpost',views.notiaddpost),
    path('Admin_view_notification', views.Admin_view_notification),
    path('Admin_edit_notification/<id>',views.Admin_edit_notification),
    path('notieditpost/<id>',views.notieditpost),
    path('notidltpost/<id>',views.notidltpost),
    path('Admin_view_complaint', views.Admin_view_complaint),
    path('Admin_reply_complaint/<id>', views.Admin_reply_complaint),
    path('complaintreplypost/<id>',views.complaintreplypost),
    path('Admin_add_event', views.Admin_add_event),
    path('eventaddpost',views.eventaddpost),
    path('Admin_view_event', views.Admin_view_event),
    path('Admin_edit_event/<id>', views.Admin_edit_event),
    path('eventeditpost/<id>',views.eventeditpost),
    path('eventdlt/<id>',views.eventdlt),
    path('Admin_prize_events/<id>', views.Admin_prize_events),
    path('eventprizepost/<id>',views.eventprizepost),
    path('prize_view',views.prize_view),
    path('Admin_view_participants/<id>', views.Admin_view_participants),

    path('Faculty_home', views.Faculty_home),
    path('Faculty_alloc_subject',views.Faculty_alloc_subject),
    path('Faculty_add_material/<id>',views.Faculty_add_material),
    path('materialaddpost/<id>',views.materialaddpost),
    path('Faculty_view_material',views.Faculty_view_material),
    path('Faculty_edit_material/<id>',views.Faculty_edit_material),
    path('materialeditpost/<id>',views.materialeditpost),
    path('materialdlt/<id>',views.materialdlt),
    path('Faculty_add_assignment/<id>',views.Faculty_add_assignment),
    path('assignmentaddpost/<id>',views.assignmentaddpost),
    path('Faculty_view_assignment', views.Faculty_view_assignment),
    path('Faculty_edit_assignment/<id>', views.Faculty_edit_assignment),
    path('assignmenteditpost/<id>',views.assignmenteditpost),
    path('assignmentdlt/<id>',views.assignmentdlt),
    path('Faculty_view_notification',views.Faculty_view_notification),
    path('Faculty_view_event',views.Faculty_view_event),
    path('Faculty_view_participants',views.Faculty_view_participants),
    path('Faculty_result_event',views.Faculty_result_event),
    path('Faculty_view_feedback',views.Faculty_view_feedback),
    path('Faculty_add_attendance/<id>',views.Faculty_add_attendance),
    path('attendanceaddpost/<id>',views.attendanceaddpost),
    path('faculty_view_attendance',views.faculty_view_attendance),
    path('attendancedlt/<id>',views.attendancedlt),
    path('faculty_view_intstud/<id>',views.faculty_view_intstud),
    path('Faculty_add_intmark/<id>',views.Faculty_add_intmark),
    path('intmarkaddpost/<id>',views.intmarkaddpost),
    path('Faculty_view_intmark', views.Faculty_view_intmark),
    path('Faculty_edit_intmark/<id>', views.Faculty_edit_intmark),
    path('intmarkeditpost/<id>',views.intmarkeditpost),
    path('intmarkdlt/<id>',views.intmarkdlt),
    path('changepwdf',views.changepwdf),
    path('changepwdfpost',views.changepwdfpost),
    path('userlogin/',views.userlogin),
    path('usr_view_profile',views.usr_view_profile),
    path('usr_view_subject',views.usr_view_subject),
    path('add_previous_notes',views.add_previous_notes),
    path('ai_lecture_notes',views.ai_lecture_notes),
    # path('chatbot',views.chatbot),
    path('dlt_previous_notes',views.dlt_previous_notes),
    path('edit_previous_notes',views.edit_previous_notes),
    path('group_chat',views.group_chat),
    path('make_payments',views.make_payments),
    path('register_events',views.register_events),
    path('sent_compliants',views.sent_compliants),
    path('sent_feedback',views.sent_feedback),
    path('student_home',views.student_home),
    path('verify_request_notes',views.verify_request_notes),
    path('view_approved_request',views.view_approved_request),
    path('view_assignments',views.view_assignments),
    path('view_attendance',views.view_attendance),
    path('view_faculty',views.view_faculty),
    path('view_events',views.view_events),
    path('view_intmarks',views.view_intmarks),
    path('view_materials',views.view_materials),
    path('view_my_previous_notes',views.view_my_previous_notes),
    path('view_notifications',views.view_notifications),
    path('view_ordered_previousnotes',views.view_ordered_previousnotes),
    path('view_others_previousnotes',views.view_others_previousnotes),
    path('view_replies',views.view_replies),
    path('view_request_notes',views.view_request_notes),
    path('view_event_results',views.view_event_results),
    path('send_request_for_notes',views.send_request_for_notes),
    path('accept_request',views.accept_request),
    path('reject_request',views.reject_request),
    path('forgotemail',views.forgotemail),
    path('forgotpass',views.forgotpass),
    path('forgotpassword',views.forgotpassword),
    path('forgotpasswordbuttonclick',views.forgotpasswordbuttonclick),
    path('otp',views.otp),
    path('otpbuttonclick',views.otpbuttonclick),
    path('forgotpswdpswed',views.forgotpswdpswed),
    path('forgotpswdpswedbuttonclick',views.forgotpswdpswedbuttonclick),
    path('user_sendchat',views.user_sendchat),
    path('user_viewchat',views.user_viewchat),
    path('view_group',views.view_group),
    path('user_sendchatbot',views.user_sendchatbot),
    path('user_viewchatbot',views.user_viewchatbot),
    
    # Text Summarization & Correction Endpoints
    path('api/summarize-text', views.summarize_text),
    path('api/summarize-bullets', views.summarize_bullets),
    path('api/correct-text', views.correct_extracted_text),
    path('api/process-pdf', views.process_pdf_file),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)